=== andsal22/erronka2/htdocs/inventario.dtd
<!ELEMENT Inventario (PC|Periferico|Equipamiento|Accesorio|Impresora|Proyector|Scanner|Servidor)*>

<!ELEMENT PC (Modelo, ComponentesBasicos)>
<!ATTLIST PC añoCompra CDATA #REQUIRED
               proveedor CDATA #REQUIRED>

<!ELEMENT ComponentesBasicos (CPU, RAM, DiscoDuro, TarjetaGrafica)>

<!ELEMENT Periferico (Modelo, Ano, Caracteristicas)>
<!ATTLIST Periferico añoCompra CDATA #REQUIRED
                   proveedor CDATA #REQUIRED>

<!ELEMENT Equipamiento (Tipo, Modelo, Ano, Caracteristicas)>
<!ATTLIST Equipamiento añoCompra CDATA #REQUIRED
                      proveedor CDATA #REQUIRED>

<!ELEMENT Accesorio (Tipo, Modelo, Ano, Caracteristicas)>
<!ATTLIST Accesorio añoCompra CDATA #REQUIRED
                   proveedor CDATA #REQUIRED>

<!ELEMENT Impresora (Modelo, Ano, Caracteristicas)>
<!ATTLIST Impresora añoCompra CDATA #REQUIRED
                   proveedor CDATA #REQUIRED>

<!ELEMENT Proyector (Modelo, Ano, Caracteristicas)>
<!ATTLIST Proyector añoCompra CDATA #REQUIRED
                   proveedor CDATA #REQUIRED>

<!ELEMENT Scanner (Modelo, Ano, Caracteristicas)>
<!ATTLIST Scanner añoCompra CDATA #REQUIRED
                  proveedor CDATA #REQUIRED>

<!ELEMENT Servidor (Modelo, Ano, Caracteristicas)>
<!ATTLIST Servidor añoCompra CDATA #REQUIRED
                   proveedor CDATA #REQUIRED
                   ip CDATA #IMPLIED>

<!ELEMENT Modelo (#PCDATA)>
<!ELEMENT CPU (#PCDATA)>
<!ELEMENT RAM (#PCDATA)>
<!ELEMENT DiscoDuro (#PCDATA)>
<!ELEMENT TarjetaGrafica (#PCDATA)>
<!ELEMENT Ano (#PCDATA)>
<!ELEMENT Caracteristicas (#PCDATA)>
<!ELEMENT Tipo (#PCDATA)>

=== andsal22/erronka2/htdocs/equipment.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Inventario SYSTEM "inventario.dtd">
<?xml-stylesheet type="text/xsl" href="equipment.xsl"?>

<Inventario>
    <Equipamiento añoCompra="2016" proveedor="ProveedorE">
        <Tipo>Switch</Tipo>
        <Modelo>HP ProCurve 2843</Modelo>
        <Ano>2016</Ano>
        <Caracteristicas>48 Puertos 100Mbps Gestionable</Caracteristicas>
        <Image path="../img/network/1.png"/>
    </Equipamiento>
    <Equipamiento añoCompra="2020" proveedor="ProveedorF">
        <Tipo>Router</Tipo>
        <Modelo>Cisco RouterX</Modelo>
        <Ano>2020</Ano>
        <Caracteristicas>4 Puertos Gigabit, WiFi 6</Caracteristicas>
        <Image path="../img/network/2.png"/>
    </Equipamiento>
    <Equipamiento añoCompra="2018" proveedor="ProveedorL">
        <Tipo>Switch</Tipo>
        <Modelo>Cisco Catalyst 2960</Modelo>
        <Ano>2018</Ano>
        <Caracteristicas>24 Puertos Gigabit</Caracteristicas>
        <Image path="../img/network/3.png"/>
    </Equipamiento>
    <Equipamiento añoCompra="2019" proveedor="ProveedorM">
        <Tipo>Router</Tipo>
        <Modelo>Juniper SRX240</Modelo>
        <Ano>2019</Ano>
        <Caracteristicas>8 Puertos Gigabit, VPN</Caracteristicas>
        <Image path="../img/network/4.png"/>
    </Equipamiento>
    <Equipamiento añoCompra="2019" proveedor="ProveedorM">
        <Tipo>Router</Tipo>
        <Modelo>Movistar Mitrastar GPT-2541GNAC</Modelo>
        <Ano>2022</Ano>
        <Caracteristicas>WiFi 5, 4 Ports Gigabit Ethernet</Caracteristicas>
        <Image path="../img/network/5.png"/>
    </Equipamiento>
</Inventario>

=== andsal22/erronka2/html/other.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Inventario SYSTEM "inventario.dtd">
<?xml-stylesheet type="text/xsl" href="other.xsl"?>

<Inventario>
    <Impresora añoCompra="2018" proveedor="ProveedorI">
        <Modelo>Brother ColorFUL 1369</Modelo>
        <Ano>2018</Ano>
        <Caracteristicas>Impresión a color, 600dpi, WiFi</Caracteristicas>
        <Image path="../img/other/1.png"/>
    </Impresora>
    <Proyector añoCompra="2019" proveedor="ProveedorJ">
        <Modelo>Optoma 94375FHD</Modelo>
        <Ano>2019</Ano>
        <Caracteristicas>Resolución 1080p, 3000 lúmenes</Caracteristicas>
        <Image path="../img/other/4.png"/>
    </Proyector>
    <Scanner añoCompra="2020" proveedor="ProveedorK">
        <Modelo>Epson ProScan 420</Modelo>
        <Ano>2020</Ano>
        <Caracteristicas>Escaneo a doble cara, 1200dpi</Caracteristicas>
        <Image path="../img/other/7.png"/>
    </Scanner>
    <Impresora añoCompra="2021" proveedor="ProveedorL">
        <Modelo>HP LaserJet Pro M402dn</Modelo>
        <Ano>2021</Ano>
        <Caracteristicas>Impresión láser, 1200dpi, Ethernet</Caracteristicas>
        <Image path="../img/other/2.png"/>
    </Impresora>
    <Proyector añoCompra="2022" proveedor="ProveedorM">
        <Modelo>Epson Home Cinema 2150</Modelo>
        <Ano>2022</Ano>
        <Caracteristicas>Resolución 1080p, 2500 lúmenes, Wireless</Caracteristicas>
        <Image path="../img/other/5.png"/>
    </Proyector>
    <Scanner añoCompra="2023" proveedor="ProveedorN">
        <Modelo>Canon ImageFORMULA DR-C225 II</Modelo>
        <Ano>2023</Ano>
        <Caracteristicas>Escaneo automático de documentos, 600dpi</Caracteristicas>
        <Image path="../img/other/8.png"/>
    </Scanner>
    <Impresora añoCompra="2024" proveedor="ProveedorO">
        <Modelo>Brother HL-L2320D</Modelo>
        <Ano>2024</Ano>
        <Caracteristicas>Impresión monocromática, 2400dpi, USB</Caracteristicas>
        <Image path="../img/other/3.png"/>
    </Impresora>
    <Proyector añoCompra="2025" proveedor="ProveedorP">
        <Modelo>BenQ MH530FHD</Modelo>
        <Ano>2025</Ano>
        <Caracteristicas>Resolución 1080p, 3300 lúmenes</Caracteristicas>
        <Image path="../img/other/6.png"/>
    </Proyector>
    <Scanner añoCompra="2026" proveedor="ProveedorQ">
        <Modelo>Fujitsu ScanSnap iX1500</Modelo>
        <Ano>2026</Ano>
        <Caracteristicas>Escaneo a color, 600dpi, WiFi</Caracteristicas>
        <Image path="../img/other/9.png"/>
    </Scanner>
</Inventario>

=== andsal22/erronka2/htdocs/server.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Inventario SYSTEM "inventario.dtd">
<?xml-stylesheet type="text/xsl" href="server.xsl"?>

<Inventario>
    <Servidor añoCompra="2017" proveedor="ProveedorN" ip="192.168.1.100">
        <Modelo>Dell PowerEdge R740</Modelo>
        <Ano>2017</Ano>
		 <ComponentesBasicos>
            <CPU>Intel Xeon</CPU>
            <RAM>32GB DDR4 ECC</RAM>
            <DiscoDuro>512GB SSD + 10TB HDD</DiscoDuro>
            <TarjetaGrafica>Intel HD Graphics 4600</TarjetaGrafica>
        </ComponentesBasicos>
        <Image path="../img/server/1.png"/>
    </Servidor>
    <Servidor añoCompra="2018" proveedor="ProveedorM" ip="192.168.1.101">
        <Modelo>HP ProLiant DL380 Gen10</Modelo>
        <Ano>2018</Ano>
		 <ComponentesBasicos>
            <CPU>Intel Xeon</CPU>
            <RAM>64GB DDR4 ECC</RAM>
            <DiscoDuro>1TB SSD + 8TB HDD</DiscoDuro>
            <TarjetaGrafica>NVIDIA Quadro RTX 8000</TarjetaGrafica>
        </ComponentesBasicos>
        <Image path="../img/server/2.png"/>
    </Servidor>
    <Servidor añoCompra="2019" proveedor="ProveedorO" ip="192.168.1.102">
        <Modelo>IBM System x3650 M5</Modelo>
        <Ano>2019</Ano>
		 <ComponentesBasicos>
            <CPU>Intel Xeon</CPU>
            <RAM>128GB DDR4 ECC</RAM>
            <DiscoDuro>2TB SSD + 12TB HDD</DiscoDuro>
            <TarjetaGrafica>AMD Radeon Pro WX 9100</TarjetaGrafica>
        </ComponentesBasicos>
        <Image path="../img/server/3.png"/>
    </Servidor>
    <Servidor añoCompra="2020" proveedor="ProveedorP" ip="192.168.1.103">
        <Modelo>Lenovo ThinkSystem SR650</Modelo>
        <Ano>2020</Ano>
		 <ComponentesBasicos>
            <CPU>Intel Xeon</CPU>
            <RAM>256GB DDR4 ECC</RAM>
            <DiscoDuro>4TB SSD + 16TB HDD</DiscoDuro>
            <TarjetaGrafica>AMD Radeon Pro WX 8200</TarjetaGrafica>
        </ComponentesBasicos>
        <Image path="../img/server/4.png"/>
    </Servidor>
    <Servidor añoCompra="2021" proveedor="ProveedorQ" ip="192.168.1.104">
        <Modelo>Cisco UCS C240 M5</Modelo>
        <Ano>2021</Ano>
		 <ComponentesBasicos>
            <CPU>Intel Xeon</CPU>
            <RAM>512GB DDR4 ECC</RAM>
            <DiscoDuro>8TB SSD + 20TB HDD</DiscoDuro>
            <TarjetaGrafica>NVIDIA Tesla V100</TarjetaGrafica>
        </ComponentesBasicos>
        <Image path="../img/server/5.png"/>
    </Servidor>
    <Servidor añoCompra="2022" proveedor="ProveedorR" ip="192.168.1.105">
        <Modelo>Supermicro SuperServer 10210U-TNR4T+</Modelo>
        <Ano>2022</Ano>
		 <ComponentesBasicos>
            <CPU>Intel Xeon</CPU>
            <RAM>1024GB DDR4 ECC</RAM>
            <DiscoDuro>16TB SSD + 24TB HDD</DiscoDuro>
            <TarjetaGrafica>AMD Radeon Pro WX 9100</TarjetaGrafica>
        </ComponentesBasicos>
        <Image path="../img/server/6.png"/>
    </Servidor>
</Inventario>

=== andsal22/erronka2/html/server.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Inventario SYSTEM "inventario.dtd">
<?xml-stylesheet type="text/xsl" href="server.xsl"?>

<Inventario>s
    <Servidor añoCompra="2017" proveedor="ProveedorN" ip="192.168.1.100">
        <Modelo>Dell PowerEdge R740</Modelo>
        <Ano>2017</Ano>
		 <ComponentesBasicos>
            <CPU>Intel Xeon</CPU>
            <RAM>32GB DDR4 ECC</RAM>
            <DiscoDuro>512GB SSD + 10TB HDD</DiscoDuro>
            <TarjetaGrafica>Intel HD Graphics 4600</TarjetaGrafica>
        </ComponentesBasicos>
    </Servidor>
</Inventario>
